# Writes FRENCH_REVIEW.md (TRANSLATIONS.md, "Review file") from the shipped XML: Mod/Defs (English source) and
# Mod/Languages/French/DefInjected. Run from anywhere: .\_tools\Make-FrenchReview.ps1
$root = Split-Path -Parent $PSScriptRoot
$rev = (git -C $root log -1 --format=%h -- Mod/Languages Mod/Defs).Trim()
$defs = Get-ChildItem (Join-Path $root 'Mod\Defs') -Filter *.xml | ForEach-Object { [xml](Get-Content $_.FullName -Raw -Encoding UTF8) }

function Get-English($defName, $field) {
  foreach ($d in $defs) {
    foreach ($def in $d.Defs.ChildNodes) {
      if ($def.defName -eq $defName -and $def.$field) { return $def.$field }
    }
  }
  return ''
}
function Cell($s) { $s.Replace('\n', '<br>').Replace('|', '\|').Trim() }

# Doubts of the session, by key: shown in the fifth column.
$flags = @{ 'CB_CrystalBall.description' = "d'eux-memes agrees in the masculine plural with no switch; on s'assied and en loisir to confirm" }

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review - Crystal Ball")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Make-FrenchReview.ps1`` from revision ``$rev``. Do not edit by hand. This mod has no source in another language: the Original column repeats the English text. French lives in ``Mod/Languages/French/DefInjected/`` only (no Keyed file, no grammar rule, no pawn token).")
[void]$out.AppendLine()

Get-ChildItem (Join-Path $root 'Mod\Languages\French\DefInjected') -Recurse -Filter *.xml | Sort-Object FullName | ForEach-Object {
  [void]$out.AppendLine("## DefInjected/$($_.Directory.Name)/$($_.Name)")
  [void]$out.AppendLine()
  [void]$out.AppendLine('| Key or path | Original | English | French | ? |')
  [void]$out.AppendLine('|---|---|---|---|---|')
  $nodes = ([xml](Get-Content $_.FullName -Raw -Encoding UTF8)).LanguageData.ChildNodes | Where-Object { $_.NodeType -eq 'Element' }
  foreach ($n in $nodes) {
    $defName, $field = $n.Name -split '\.', 2
    $en = Get-English $defName $field
    $q = ''
    if ($flags.ContainsKey($n.Name)) { $q = '? ' + $flags[$n.Name] }
    [void]$out.AppendLine("| ``$($n.Name)`` | $(Cell $en) | $(Cell $en) | $(Cell $n.InnerText) | $q |")
  }
  [void]$out.AppendLine()
}
[void]$out.AppendLine('## Review line (Virginie only)')
[void]$out.AppendLine()
[void]$out.AppendLine('| Reviewer | Date | Revision reviewed | Corrections requested |')
[void]$out.AppendLine('|---|---|---|---|')
[void]$out.AppendLine('| | | | |')
[IO.File]::WriteAllText((Join-Path $root 'FRENCH_REVIEW.md'), $out.ToString(), (New-Object Text.UTF8Encoding($false)))
